### ISSUE TITLE
Argo: Release To facet has false values (proxy ticket)

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#132]
This is a proxy ticket for sul-dlss/dor-services#234

**Comment by jmartin-sul** [comment]
PR for the dor-services part:  https://github.com/sul-dlss/dor-services/issues/240

once that's merged, we can cut a new dor-services release, and upgrade argo to use the latest dor-services.

**Comment by jmartin-sul** [comment]
dor-services PR is merged, and dor-services 5.11.1 has been released.  we should also upgrade dor_indexing_app.

**Comment by jmartin-sul** [comment]
PRs for the argo and dor_indexing_app upgrades:
https://github.com/sul-dlss/argo/pull/825
https://github.com/sul-dlss/dor_indexing_app/pull/35

@LynnMcRae, these branches are deployed to their respective stage instances, and the problem seems to go away for your example druid:  https://argo-stage.stanford.edu/catalog/druid:bb020sf5359
