### ISSUE TITLE
Playback timeline bar is obscured in Safari 13.0.5 on video objects

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/media#154]
In the newest version of Safari on MacOS, video objects do not have a playback bar that's visible, which means a user can't shuttle through a resource. Rights don't appear to matter, e.g.

https://purl.stanford.edu/sr117nq6196 (Stanford resource)
https://purl.stanford.edu/bb025pz8001 (world resource)

Audio objects look to be ok, and Safari on iOS does show a playback bar.

**Comment by jkeck** [comment]
@oceanofsound can you submit a screenshot?  I do see a bug that needs to be addressed w/ the height of the video viewers (that was caused by some recent changes), but I do see the playback bar so I want to make sure the fix I implement actually addresses the issue you're seeing.

<img width="755" alt="bb025pz8001-before-safari" src="https://user-images.githubusercontent.com/96776/78411762-9eb6ab00-75c5-11ea-99da-67d20e587ec7.png">

**Comment by jkeck** [comment]
@oceanofsound can you verify that this was fixed and comment/re-open if you're still experiencing the same problem?  Thanks!
