### ISSUE TITLE
identify exemplar fully accessioned public media objects

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#2]
- [x] video
- [x] audio

Must have purl pages with media.

Please provide druids and/or specific links to media files.

**Comment by hannahfrost** [comment]
audio: https://purl.stanford.edu/bb051hp9404 
video: https://purl.stanford.edu/bb582xs1304

Each of these are exemplary, because:
- the audio object includes an MP3 that represents our typical file specs. It should be streamable by Wowza as is.
- the audio object includes a PDF transcript, which is not uncommon for oral history audio objects and we'll need to eventually find a way to handle in sul-embed/purl
- the video object includes an MP4 that represents our typical file specs. It should be streamable by Wowza as is.
- the video object includes images of the original video tape. Almost all digitized media coming from SMPL will have one or more jp2s that we'll need to support somehow someday.
