### ISSUE TITLE
Create script to support reporting for Riverwalk Jazz license

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/media#7]
See: https://jirasul.stanford.edu/jira/browse/DEVQUEUE-24

**Comment by ndushay** [comment]
From JIRA ticket:

As of Jan 2016, there are new SoundExchange reporting requirements for SUL related to our statutory license as a noncommercial webcaster of the Riverwalk Jazz collection online. We now are required to prepare monthly reports on the number of “performances” of each song ie, each time a particular song is streamed.

We can achieve this by developing a script capable of interrogating the hourly logs that are created and stored on media@libstream.stanford.edu/var/log/ezstream/. Inputs to the script would reflect the reporting time period.

Each log files contains xml that looks like this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>StreamGuys Icecast Server</title>
</head>
<body>1,1,22,unlimited,-1,, - Show Number 067<br />1,1,20,unlimited,-1,, - Show Number 371<br /></body>
</html>
```

We need to strip out the 3-4 character alphanumeric string that follow the two instances of “Show Number” – in this example: “067” and “371" – and record these values in a format that enables us to accurately tally the number of times that these shows were streamed in a given month.

The output of this script can then be loaded into an existing spreadsheet containing the song lists for each show. And because we can assume that every song in a given show has been streamed as many as time the show number has been logged, it will be possible to meet the reporting requirements.

Sample set of a month’s worth of logs is attached.

**Comment by ndushay** [comment]
Note:  Rob Smith wrote the code to write the logs;  it may make sense to look at Rob's script / talk to Rob / edit Rob's script.

It is probably useful to keep the overall processing the same

**Comment by ndushay** [comment]
from conversation with Geoff (@oceanofsound):
- The raw files live /var/log/ezstream directory on libstream VM.
  - These files are created by a script written by @rsmith11.
- Geoff downloads the relevant dates, then fusses to get the show numbers from each channel
  - for `<body>1,1,22,unlimited,-1,, - Show Number 067<br />1,1,20,unlimited,-1,, - Show Number 371<br /></body>` :  channel 1  is show 067, channel 2 is show 371
- then sorts the show numbers to be able to visually get the counts for each show for each channel.

Desired:  
- "ideal - a file for each channel that has a list of shows sorted in numeric order followed by the show count"
- we could do this with a script on the libstream box that geoff would run, where he inputs the dates (or that just does it by the month)

more about what he is doing is here:  https://consul.stanford.edu/pages/viewpage.action?title=How+to+create+a+ROU&spaceKey=RWJ

**Comment by ndushay** [comment]
@oceanofsound @hannahfrost  questions
-  the log files are HOURLY, per day
  - how are they named / organized on the server?
- will the reporting needs always be monthly?   (should the script assume monthly or take user inputs for time frame)

**Comment by ndushay** [comment]
“You want to know how frequent the log files are?  Let me tell you about log files.  I have been very successful with log files.   Log files love me.  I am an expert on log files. We are going to have so many log files, you’ll be sick of log files."

**Comment by oceanofsound** [comment]
![lovely_logs](https://cloud.githubusercontent.com/assets/1029087/14217719/94f5d5ca-f804-11e5-8c88-f46733ff6ec8.png)

**Comment by oceanofsound** [comment]
reporting needs will be monthly, unless SoundExchange changes their reporting requirements again

**Comment by ndushay** [comment]
do they change their reporting requirements often?

**Comment by oceanofsound** [comment]
I think we're good until 2020: http://www.soundexchange.com/service-provider/commercial-webcaster/commercial-webcaster-crb/

**Comment by ndushay** [comment]
libstream box:

```
[media@libstream ~]$ java -version
-bash: java: command not found
[media@libstream ~]$ ruby -version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
-e:1: undefined local variable or method `rsion' for main:Object (NameError)
[media@libstream ~]$ rvm
-bash: rvm: command not found
```

Looks like we can write the script in:
- ruby (v1.8.7!)
- shell script
- python

**Comment by ndushay** [comment]
@oceanofsound   Code is deployed on libstream.  I have tested it and it works.   The instructions will be in the README here:  https://github.com/sul-dlss/rwj_reporting   after I get a couple more pull requests merged.  For now, here they are:

# Usage
1. log in to libstream box as media user
2. `cd rwj_reporting/current`  (end up in `home/media/rwj_reporting/current`)
3. `rake reports[160301,160331]`
   - the dates given are yymmdd format
   - the dates are inclusive
   - the square brackets and comma are required
4.  reports are written to the `home/media` directory as, e.g. `160301-160331_channel_1_usage_counts.csv` and `160301-160331_channel_2_usage_counts.csv`.  
   - You can change the directory where the reports are written by changing `home/media/rwj_reporting/shared/config/settings.yml`  output_dir

Log files are expected to be in `/var/log/ezstream`.  This directory is also configurable in `home/media/rwj_reporting/shared/config/settings.yml`

**Comment by ndushay** [comment]
@jmartin-sul and I have completed this.
