### ISSUE TITLE
Manually release embargoed content

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#70]

**Comment by ndushay** [comment]
Given today's (mixed) success with the embargo-release code, this may not still be necessary???

**Comment by LynnMcRae** [comment]
Because of the partial success, Ben will be completing the release of the 205 rather than remediate them back to embargoed.  We'll either get more naturally or can embargo more in prod when you are ready to try the prod script again.

**Comment by blalbrit** [comment]
spot-checking as I go, the following steps successfully replace the rightsMD:
item=Dor::Item.find("druid:#{druid}")
item.release_embargo("application::accessionWF:embargo-release")
item.save

So maybe the versioning stuff is causing problems?

**Comment by ndushay** [comment]
We were doing  `item.close_version` before the `item.save`  when we ran manually.  It appeared to keep the embargo info in the rights_xml.

The "script"  does `item.save` before  `item.close_version` and that also seems to keep the embargo info in the rights_xml.

Are you suggesting that `item.open_new_version` is what's causing us grief?

**Comment by blalbrit** [comment]
I think what I'm suggesting is that I'm doing item.save (which successfully updates the datastream - that is, rightsMD is updated with the post-embargo data). I'm currently then - opening & closing a version in Argo rather than through the .open_new_version or .close_version methods.

This is successfully doing what we want it to do... so wondering if the version methods are what are messing us up. That's about as deep as my thought went.

**Comment by ndushay** [comment]
👍   info for the new ticket.

**Comment by blalbrit** [comment]
203 objects manually released (2 were in a registered-only state).
