### ISSUE TITLE
create test data for location restricted content

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#77]
Currently we have only one location restricted file in the Jessie says No object.

At object and file level

types of objects
- file
- image 
- media

also intersection of all these with stanford-only objects.

**Comment by LynnMcRae** [comment]
Two test objects for media now available (still working on others). I have started to use "lathrop" as a test location that we can make fungible for testing so that "spec" can get its real definition as that comes along.

https://purl-test.stanford.edu/vf466bd3249 - simple one video object, with location=lathrop

https://purl-test.stanford.edu/fq961jm6386 - repurposed Cat Chattering object to be world visible by default (first video) and location-specific restriction at the resource level on second video.

Note that both location restrictions are location-only and do not involve Stanford-only, but embed currently wants me to login anyway.

**Comment by LynnMcRae** [comment]
Two test objects for image are now available, using "lathrop" as the location:

https://purl-test.stanford.edu/gc810cm7976 - single image object with object level location restriction

https://purl-test.stanford.edu/pn861pp0444 - two image object, the first governed by object-level world access, the second with a file-level location restriction.

**Comment by LynnMcRae** [comment]
Two new media test objects for "Stanford OR location"

https://argo-stage.stanford.edu/catalog/druid:vs077pq2501 - one video, Stanford OR location=lathrop at the object level.

https://purl-test.stanford.edu/gm746xg1831 - two videos, the first is world (object default), the second is Stanford OR location=lathrop at the file level.

**Comment by LynnMcRae** [comment]
Two test objects for content-type=file with location restrictions

https://purl-test.stanford.edu/vg385nf6171 -- Ode on the Death of a Favourite Cat, Drowned in a Tub of Gold Fishes : A test object, one file resource, object restricted to location=lathrop

https://purl-test.stanford.edu/fn354ht3703 -- Pangur Bán ("The Scholar and the Cat") : A test object, two file resources, 2nd restricted to location=lathrop

**Comment by LynnMcRae** [comment]
Test objects that combine location with no-download, two at object/default level, two at file level. 

New media object:
https://purl-test.stanford.edu/mq099tt8571 -- Cat Massage! (Test media object, object default location+no-download)

New image object:
https://purl-test.stanford.edu/jz517dz5155 -- Tatra Automobile spotted on campus (Test image object, first image world+no-download, second image location+no-download)

Updated media object:
Added third video to https://purl-test.stanford.edu/gm746xg1831 (lathrop) with location+no-download

Updated image object:
Added third image to https://purl-test.stanford.edu/pn861pp0444 (pies) with location+no-download

**Comment by LynnMcRae** [comment]
information about test objects for rights/locations gathered togetger at https://consul.stanford.edu/display/chimera/Test+objects+for+rights+metadata
